// Generated by Text-to-CAD from prompt:
// an M10 bolt 40 mm long
$fn = 64;

module Bolt() {
    translate([0, 0, 40]) {
    cylinder(h=7, r=9, $fn=$fn);
    }
cylinder(h=40, r=5, $fn=$fn);
}

Bolt();
