// Generated by Text-to-CAD from prompt:
// a 4.5 m long sedan, 1.85 m wide
$fn = 64;

module Car() {
    translate([0, 0, 320]) {
    cube([4500, 1850, 797.5]);
    }
    translate([1260, 92.5, 1117.5]) {
    cube([2025, 1665, 652.5]);
    }
    translate([810, 0, 320]) rotate(a=90, v=[1, 0, 0]) {
    cylinder(h=222, r=320, $fn=$fn);
    }
    translate([810, 1850, 320]) rotate(a=90, v=[1, 0, 0]) {
    cylinder(h=222, r=320, $fn=$fn);
    }
    translate([3690, 0, 320]) rotate(a=90, v=[1, 0, 0]) {
    cylinder(h=222, r=320, $fn=$fn);
    }
    translate([3690, 1850, 320]) rotate(a=90, v=[1, 0, 0]) {
    cylinder(h=222, r=320, $fn=$fn);
    }
}

Car();
