// Generated by Text-to-CAD from prompt:
// a CPU cooler, 50 mm base, 20 fins
$fn = 64;

module CPUHeatsink() {
cube([40, 40, 4]);
for (i = [0 : 15]) translate([2.5*i, 0*i, 0*i]) {
    translate([0, 0, 4]) {
        cube([1.5, 40, 30]);
    }
}
    translate([0, 0, -2]) {
    cube([38, 38, 2]);
    }
    translate([11, 11, -0.8]) {
    cube([18, 18, 0.8]);
    }
}

CPUHeatsink();
