// Generated by Text-to-CAD from prompt:
// a project enclosure 120 x 80 x 40 mm
$fn = 64;

module Enclosure() {
difference() {
    cube([40, 80, 40]);
    translate([2.5, 2.5, 2.5]) {
        cube([35, 75, 40]);
    }
}
}

Enclosure();
