// Generated by Text-to-CAD from prompt:
// a 6 bolt flange 120 mm diameter
$fn = 64;

module Flange() {
difference() {
    cylinder(h=10, r=60, $fn=$fn);
    cylinder(h=10, r=25, $fn=$fn);
    for (i = [0 : 5]) rotate([0, 0, 360.0 / 6 * i]) {
        translate([42.5, 0, 0]) {
            cylinder(h=10, r=5, $fn=$fn);
        }
    }
}
}

Flange();
