// Generated by Text-to-CAD from prompt:
// a 24 tooth gear
$fn = 64;

module Gear() {
difference() {
    union() {
        cylinder(h=8, r=24, $fn=$fn);
        for (i = [0 : 23]) rotate([0, 0, 360.0 / 24 * i]) {
            translate([22.8, -1.6, 0]) {
                cube([2.4, 3.2, 8]);
            }
        }
    }
    cylinder(h=8, r=3, $fn=$fn);
}
}

Gear();
