// Generated by Text-to-CAD from prompt:
// a GPU heatsink with 24 fins
$fn = 64;

module GPUHeatsink() {
cube([55, 55, 4]);
for (i = [0 : 23]) translate([2.2917*i, 0*i, 0*i]) {
    translate([0, 0, 4]) {
        cube([1.375, 55, 40]);
    }
}
    translate([0, 0, -2]) {
    cube([52.25, 52.25, 2]);
    }
    translate([15.125, 15.125, -0.8]) {
    cube([24.75, 24.75, 0.8]);
    }
}

GPUHeatsink();
