// Generated by Text-to-CAD from prompt:
// a turbofan jet engine 3 m long with 28 blades
$fn = 64;

module JetEngine() {
difference() {
    cylinder(h=3000, r=1620, $fn=$fn);
    cylinder(h=3000, r=1500, $fn=$fn);
}
cylinder(h=1200, r1=405, r2=0, $fn=$fn);
for (i = [0 : 27]) rotate([0, 0, 360.0 / 28 * i]) {
    translate([675, 0, 300]) {
        cube([783.75, 120, 540]);
    }
}
    translate([0, 0, 600]) {
    cylinder(h=2400, r=675, $fn=$fn);
    }
    translate([0, 0, 3000]) {
    cylinder(h=1500, r1=540, r2=135, $fn=$fn);
    }
}

JetEngine();
