// Generated by Text-to-CAD from prompt:
// a 3 blade propeller 300 mm diameter
$fn = 64;

module Propeller() {
cylinder(h=24, r=20, $fn=$fn);
for (i = [0 : 2]) rotate([0, 0, 360.0 / 3 * i]) {
    translate([20, 0, 7.2]) rotate(a=18, v=[1, 0, 0]) {
        cube([130, 18, 10]);
    }
}
}

Propeller();
