// Generated by Text-to-CAD from prompt:
// a 2 metre rocket with 6 fins and 2 stages
$fn = 64;

module Rocket() {
    translate([0, 0, 1750]) {
    cylinder(h=250, r1=50, r2=0, $fn=$fn);
    }
cylinder(h=875, r=50, $fn=$fn);
    translate([0, 0, 875]) {
    cylinder(h=875, r=50, $fn=$fn);
    }
for (i = [0 : 5]) rotate([0, 0, 360.0 / 6 * i]) {
    translate([50, 0, 0]) {
        cube([90, 4, 120]);
    }
}
    translate([0, 0, -80]) {
    cylinder(h=80, r1=17.5, r2=35, $fn=$fn);
    }
}

Rocket();
