"""
Design -> OpenSCAD source.

OpenSCAD is a pure-text CAD language with a real CSG engine, so this exporter
gives *true* boolean results (union/difference/intersection) with no FreeCAD
dependency. The emitted .scad file can be opened in OpenSCAD or rendered to
STL headlessly with ``openscad -o out.stl in.scad``.
"""

from __future__ import annotations

from typing import List

from . import spec


def _fmt(x: float) -> str:
    return f"{x:.4f}".rstrip("0").rstrip(".")


def _v(vec) -> str:
    return "[" + ", ".join(_fmt(c) for c in vec) + "]"


def _wrap_placement(p: "spec.Placement", body: List[str], indent: str) -> List[str]:
    """Emit translate(...) rotate(...) wrappers around a child body."""
    needs_t = any(abs(c) > 1e-9 for c in p.pos)
    needs_r = abs(p.angle) > 1e-9
    head = ""
    if needs_t:
        head += f"translate({_v(p.pos)}) "
    if needs_r:
        head += f"rotate(a={_fmt(p.angle)}, v={_v(p.axis)}) "
    if not head:
        return body
    out = [indent + head + "{"]
    out += ["    " + line for line in body]
    out += [indent + "}"]
    return out


def _emit(node: "spec.Solid", indent: str = "") -> List[str]:
    k = node.kind
    if k == "box":
        body = [f"cube({_v((node.length, node.width, node.height))});"]
    elif k == "cylinder":
        body = [f"cylinder(h={_fmt(node.height)}, r={_fmt(node.radius)}, $fn=$fn);"]
    elif k == "cone":
        body = [f"cylinder(h={_fmt(node.height)}, r1={_fmt(node.radius1)}, "
                f"r2={_fmt(node.radius2)}, $fn=$fn);"]
    elif k == "sphere":
        body = [f"sphere(r={_fmt(node.radius)}, $fn=$fn);"]
    elif k == "torus":
        body = [f"rotate_extrude($fn=$fn) translate([{_fmt(node.radius1)}, 0, 0]) "
                f"circle(r={_fmt(node.radius2)}, $fn=$fn);"]
    elif k == "boolean":
        op = {"union": "union", "cut": "difference", "common": "intersection"}[node.op]
        body = [op + "() {"]
        for c in node.children:
            body += ["    " + line for line in _emit(c)]
        body += ["}"]
    elif k == "polar_array":
        body = [f"for (i = [0 : {node.count - 1}]) "
                f"rotate([0, 0, 360.0 / {node.count} * i]) {{"]
        body += ["    " + line for line in _emit(node.base)]
        body += ["}"]
    elif k == "linear_array":
        dx, dy, dz = node.spacing
        body = [f"for (i = [0 : {node.count - 1}]) "
                f"translate([{_fmt(dx)}*i, {_fmt(dy)}*i, {_fmt(dz)}*i]) {{"]
        body += ["    " + line for line in _emit(node.base)]
        body += ["}"]
    else:
        raise ValueError(f"Unknown spec kind: {k}")

    return _wrap_placement(node.placement, body, indent)


def to_scad(design: "spec.Design", fn: int = 64) -> str:
    lines = [
        f"// Generated by Text-to-CAD from prompt:",
        f"// {design.meta.get('prompt', design.name)}",
        f"$fn = {fn};",
        "",
        f"module {design.name.replace(' ', '_')}() {{",
    ]
    for node in design.features:
        for ln in _emit(node, indent="    "):
            lines.append(ln)
    lines += ["}", "", f"{design.name.replace(' ', '_')}();", ""]
    return "\n".join(lines)


def write_scad(design: "spec.Design", path: str, fn: int = 64) -> str:
    with open(path, "w", encoding="utf-8") as f:
        f.write(to_scad(design, fn=fn))
    return path
